### ISSUE TITLE
Ideas for Replacing the DB1042 Container

### ISSUE THREAD

**Issue by poftadeh** [Seneca-CDOT/ostep-dashboard#59]
The `DB1042` container on the dashboard used to list the bookings for the meeting room back at Seneca@York. Since the move, this feature is no longer needed. The empty space on the dashboard can be replaced with a new feature. Some past suggestions were: 

* Upcoming partner meetings 
* Project stats 
* RA stats 
* Tim Horton's wait time estimator 
* A list of issues from each project tagged with `help wanted` (for collaboration between projects)
* List of PRs that are pending review.

I'll open the discussion here for more suggestions.

**Comment by belavina** [comment]
I vote numero 5 (A list of issues from each project tagged with help wanted (for collaboration between projects) * List PRs that are pending review.) since I think this will help with cross-project collaboration & make knowledge transfer less painful. 

Another idea is to have suggestions for presentation topics (populated by the devs).

**Comment by miggs125** [comment]
weather api?

**Comment by ctyler** [comment]
I think the meeting area in the corner of K2020 will be the "new T1042" (never got used to that "DB" nomenclature), so we could just repurpose it to that.

I like the idea of PRs or upcoming partner meetings, too.

**Comment by poftadeh** [comment]
Two new additions are in progress: a `help wanted` panel, and a `PR reminder` panel. Progress can be tracked on the project [Kanban board](https://github.com/Seneca-CDOT/ostep-dashboard/projects/3).
